# Generated by Django 5.0.6 on 2024-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primenumbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primenumber',
            name='number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
