# Generated by Django 5.0.6 on 2024-05-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primenumbers', '0002_primenumber_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimeNumber',
            new_name='Number',
        ),
    ]
