# Generated by Django 5.0.6 on 2024-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primenumbers', '0004_number_isprime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='isPrime',
            field=models.BooleanField(),
        ),
    ]
